[build]
  base = "/"
  command = "npm ci && npm install && npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173

[context.production.environment]
  NODE_ENV = "production"
