[build]
  base = "/"
  command = "npm install --include=dev && npm run build"
  publish = "dist"
  node = "18.17.0"

[build.environment]
  NODE_ENV = "production"
  CI = "false"

[dev]
  command = "npm run dev"
  port = 3000
