[build]
  base = "/"
  command = "npm install && npm run build"
  publish = "dist"
  node = "18.17.0"

[build.environment]
  NODE_ENV = "production"
  CI = "false"

[build.environment.production]
  NODE_ENV = "production"

[build.environment.development]
  NODE_ENV = "development"

[dev]
  command = "npm start"
  port = 3000
