[build]
  base = "/"
  command = "rm -rf node_modules build && npm install && npm run build"
  publish = "build"
  node = "14.17.0"

[build.environment]
  NODE_ENV = "production"
  CI = "false"

[dev]
  command = "npm start"
  port = 3000
