[build]
  base = "/"
  command = "npm install && node --max-old-space-size=4096 node_modules/vite/bin/vite.js build"
  publish = "build"
  node = "16.20.2"

[build.environment]
  NODE_ENV = "production"
  CI = "false"

[dev]
  command = "npm start"
  port = 3000
