[build]
  base = "/"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"
  node = "18"

[dev]
  command = "npm start"
  port = 3000

[context.production.environment]
  NODE_ENV = "production"
