[build]
  base = "/"
  command = "npm install && npm run build"
  publish = "build"
  node = "18.19.0"

[dev]
  command = "npm start"
  port = 3000

[context.production.environment]
  NODE_ENV = "production"
