[build]
  base = "/"
  command = "yarn install && yarn build"
  publish = "build"
  node = "16.20.2"

[build.environment]
  NODE_ENV = "production"
  CI = "false"

[dev]
  command = "npm start"
  port = 3000
