[build]
  base = "/"
  command = "chmod +x build.sh && ./build.sh"
  publish = "dist"
  node = "18"

[dev]
  command = "npm run dev"
  port = 5173

[context.production.environment]
  NODE_ENV = "production"
  VITE_ENV = "production"
